# Generated by Django 3.2.5 on 2021-07-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='diary',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='sell',
        ),
        migrations.AddField(
            model_name='diary',
            name='buy',
            field=models.ManyToManyField(related_name='item_bought', to='diary.Corporation'),
        ),
        migrations.AddField(
            model_name='diary',
            name='sell',
            field=models.ManyToManyField(related_name='item_sold', to='diary.Corporation'),
        ),
    ]
