# Generated by Django 3.2.5 on 2021-08-06 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='diary',
            name='sell',
            field=models.ManyToManyField(related_name='item_sold', to='diary.Corporation'),
        ),
    ]
