# Generated by Django 3.2.5 on 2021-08-10 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buysell',
            old_name='buysell',
            new_name='bs',
        ),
    ]
