# Generated by Django 3.2.5 on 2021-08-07 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='profile',
        ),
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
