# Generated by Django 3.2.5 on 2021-07-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20210728_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
