# Generated by Django 3.2.5 on 2021-08-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20210811_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='up',
            new_name='interestedUser',
        ),
    ]
