# Generated by Django 3.2.5 on 2021-08-12 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0004_rename_up_diary_interesteduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCorporation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUsedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.corporation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='corporation',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, through='diary.FavoriteCorporation', to=settings.AUTH_USER_MODEL),
        ),
    ]
