# Generated by Django 3.2.5 on 2021-08-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20210807_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='buy',
            field=models.ManyToManyField(blank=True, null=True, related_name='item_bought', to='diary.Corporation'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='sell',
            field=models.ManyToManyField(blank=True, null=True, related_name='item_sold', to='diary.Corporation'),
        ),
    ]
