# Generated by Django 3.2.5 on 2021-08-15 03:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0005_auto_20210812_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritecorporation',
            unique_together={('user', 'corporation')},
        ),
    ]
