# Generated by Django 3.2.5 on 2021-08-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20210807_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='logo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
