# Generated by Django 3.2.5 on 2021-08-15 05:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0006_alter_favoritecorporation_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'diary')},
        ),
    ]
