# Generated by Django 3.2.5 on 2021-08-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20210815_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='code',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
    ]
