# Generated by Django 3.2.5 on 2021-08-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_corporation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='logo',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
