# Generated by Django 3.2.5 on 2021-08-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_alter_corporation_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buysell',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='buysell',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='corporation',
            name='logo',
            field=models.ImageField(upload_to='logos'),
        ),
    ]
