# Generated by Django 3.2.5 on 2021-08-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_auto_20210816_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buysell',
            name='bs',
        ),
        migrations.AddField(
            model_name='buysell',
            name='category',
            field=models.CharField(choices=[('buy', '매수'), ('sell', '매도')], default='buy', max_length=50),
            preserve_default=False,
        ),
    ]
